import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-directiva',
  templateUrl: './directiva.component.html',
  styleUrls: ['./directiva.component.css']
})
export class DirectivaComponent {

  constructor() { }
   Pokemon:any = [
    {id:1, nombre:'Bulbasaur', tipo:'Monstruo', poder:226},
    {id:2, nombre:'Ivysaur', tipo:'Monstruo', poder:227},
    {id:3, nombre:'Venusaur', tipo:'Monstruo', poder:228},
    {id:4, nombre:'Charmander', tipo:'Monstruo', poder:229},
    {id:5, nombre:'Charmeleon', tipo:'Monstruo', poder:230},
    {id:6, nombre:'Charizard', tipo:'Monstruo', poder:231},
    {id:7, nombre:'Squirtle', tipo:'Monstruo', poder:232},
    {id:8, nombre:'Wartortle', tipo:'Monstruo', poder:233},
    {id:9, nombre:'Blastoise', tipo:'Monstruo', poder:234},
    {id:10, nombre:'Caterpie', tipo:'Bicho', poder:24},
    {id:11, nombre:'Metapod', tipo:'Bicho', poder:25},
    {id:12, nombre:'Butterfree', tipo:'Bicho', poder:26},
    {id:13, nombre:'Weedle', tipo:'Bicho', poder:27},
    {id:14, nombre:'Kakuna', tipo:'Bicho', poder:28},
    {id:15, nombre:'Beedrill', tipo:'Bicho', poder:29},
    {id:16, nombre:'Pidgey', tipo:'Volador', poder:10},
    {id:17, nombre:'Pidgeotto', tipo:'Volador', poder:11},
    {id:18, nombre:'Pidgeot', tipo:'Volador', poder:12},
    {id:19, nombre:'Rattata', tipo:'Campo', poder:17},
    {id:20, nombre:'Raticate', tipo:'Campo', poder:18},
    {id:21, nombre:'Spearow', tipo:'Volador', poder:13},
    {id:22, nombre:'Fearow', tipo:'Volador', poder:14},
    {id:23, nombre:'Ekans', tipo:'Campo', poder:50},
    {id:24, nombre:'Arbok', tipo:'Campo', poder:51},
    {id:25, nombre:'Pikachu', tipo:'Campo', poder:22},
    {id:26, nombre:'Raichu', tipo:'Campo', poder:23},
    {id:27, nombre:'Sandshrew', tipo:'Campo', poder:48},
    {id:28, nombre:'Sandslash', tipo:'Campo', poder:49},
    {id:29, nombre:'Nidoran♀', tipo:'Monstruo', poder:95},
    {id:30, nombre:'Nidorina', tipo:'Ninguno', poder:96},
    {id:31, nombre:'Nidoqueen', tipo:'Ninguno', poder:97},
    {id:32, nombre:'Nidoran♂', tipo:'Monstruo', poder:98},
    {id:33, nombre:'Nidorino', tipo:'Monstruo', poder:99},
    {id:34, nombre:'Nidoking', tipo:'Monstruo', poder:100},
    {id:35, nombre:'Clefairy', tipo:'Hada', poder:41},
    {id:36, nombre:'Clefable', tipo:'Hada', poder:42},
    {id:37, nombre:'Vulpix', tipo:'Campo', poder:125},
    {id:38, nombre:'Ninetales', tipo:'Campo', poder:126},
    {id:39, nombre:'Jigglypuff', tipo:'Hada', poder:44},
    {id:40, nombre:'Wigglytuff', tipo:'Hada', poder:45},
    {id:41, nombre:'Zubat', tipo:'Volador', poder:37},
    {id:42, nombre:'Golbat', tipo:'Volador', poder:38},
    {id:43, nombre:'Oddish', tipo:'Planta', poder:83},
    {id:44, nombre:'Gloom', tipo:'Planta', poder:84},
    {id:45, nombre:'Vileplume', tipo:'Planta', poder:85},
    {id:46, nombre:'Paras', tipo:'Bicho', poder:70},
    {id:47, nombre:'Parasect', tipo:'Bicho', poder:71},
    {id:48, nombre:'Venonat', tipo:'Bicho', poder:108},
    {id:49, nombre:'Venomoth', tipo:'Bicho', poder:109},
    {id:50, nombre:'Diglett', tipo:'Campo', poder:132},
    {id:51, nombre:'Dugtrio', tipo:'Campo', poder:133},
    {id:52, nombre:'Meowth', tipo:'Campo', poder:136},
    {id:53, nombre:'Persian', tipo:'Campo', poder:137},
    {id:54, nombre:'Psyduck', tipo:'Agua 1', poder:138},
    {id:55, nombre:'Golduck', tipo:'Agua 1', poder:139},
    {id:56, nombre:'Mankey', tipo:'Campo', poder:134},
    {id:57, nombre:'Primeape', tipo:'Campo', poder:135},
    {id:58, nombre:'Growlithe', tipo:'Campo', poder:127},
    {id:59, nombre:'Arcanine', tipo:'Campo', poder:128},
    {id:60, nombre:'Poliwag', tipo:'Agua 1', poder:72},
    {id:61, nombre:'Poliwhirl', tipo:'Agua 1', poder:73},
    {id:62, nombre:'Poliwrath', tipo:'Agua 1', poder:74},
    {id:63, nombre:'Abra', tipo:'Humanoide', poder:89},
    {id:64, nombre:'Kadabra', tipo:'Humanoide', poder:90},
    {id:65, nombre:'Alakazam', tipo:'Humanoide', poder:91},
    {id:66, nombre:'Machop', tipo:'Humanoide', poder:140},
    {id:67, nombre:'Machoke', tipo:'Humanoide', poder:141},
    {id:68, nombre:'Machamp', tipo:'Humanoide', poder:142},
    {id:69, nombre:'Bellsprout', tipo:'Planta', poder:64},
    {id:70, nombre:'Weepinbell', tipo:'Planta', poder:65},
    {id:71, nombre:'Victreebel', tipo:'Planta', poder:66},
    {id:72, nombre:'Tentacool', tipo:'Agua 3', poder:162},
    {id:73, nombre:'Tentacruel', tipo:'Agua 3', poder:163},
    {id:74, nombre:'Geodude', tipo:'Mineral', poder:34},
    {id:75, nombre:'Graveler', tipo:'Mineral', poder:35},
    {id:76, nombre:'Golem', tipo:'Mineral', poder:36},
    {id:77, nombre:'Ponyta', tipo:'Campo', poder:201},
    {id:78, nombre:'Rapidash', tipo:'Campo', poder:202},
    {id:79, nombre:'Slowpoke', tipo:'Monstruo', poder:80},
    {id:80, nombre:'Slowbro', tipo:'Monstruo', poder:81},
    {id:81, nombre:'Magnemite', tipo:'Mineral', poder:118},
    {id:82, nombre:'Magneton', tipo:'Mineral', poder:119},
    {id:83, nombre:'Farfetch', tipo:'Volador', poder:158},
    {id:84, nombre:'Doduo', tipo:'Volador', poder:199},
    {id:85, nombre:'Dodrio', tipo:'Volador', poder:200},
    {id:86, nombre:'Seel', tipo:'Agua 1', poder:176},
    {id:87, nombre:'Dewgong', tipo:'Agua 1', poder:177},
    {id:88, nombre:'Grimer', tipo:'Amorfo', poder:116},
    {id:89, nombre:'Muk', tipo:'Amorfo', poder:117},
    {id:90, nombre:'Shellder', tipo:'Agua 3', poder:169},
    {id:91, nombre:'Cloyster', tipo:'Agua 3', poder:170},
    {id:92, nombre:'Gastly', tipo:'Amorfo', poder:58},
    {id:93, nombre:'Haunter', tipo:'Amorfo', poder:59},
    {id:94, nombre:'Gengar', tipo:'Amorfo', poder:60},
    {id:95, nombre:'Onix', tipo:'Mineral', poder:62},
    {id:96, nombre:'Drowzee', tipo:'Humanoide', poder:87},
    {id:97, nombre:'Hypno', tipo:'Humanoide', poder:88},
    {id:98, nombre:'Krabby', tipo:'Agua 3', poder:164},
    {id:99, nombre:'Kingler', tipo:'Agua 3', poder:165},
    {id:100, nombre:'Voltorb', tipo:'Mineral', poder:120},
    {id:101, nombre:'Electrode', tipo:'Mineral', poder:121},
    {id:102, nombre:'Exeggcute', tipo:'Planta', poder:104},
    {id:103, nombre:'Exeggutor', tipo:'Planta', poder:105},
    {id:104, nombre:'Cubone', tipo:'Monstruo', poder:203},
    {id:105, nombre:'Marowak', tipo:'Monstruo', poder:204},
    {id:106, nombre:'Hitmonlee', tipo:'Humanoide', poder:144},
    {id:107, nombre:'Hitmonchan', tipo:'Humanoide', poder:145},
    {id:108, nombre:'Lickitung', tipo:'Monstruo', poder:178},
    {id:109, nombre:'Koffing', tipo:'Amorfo', poder:114},
    {id:110, nombre:'Weezing', tipo:'Amorfo', poder:115},
    {id:111, nombre:'Rhyhorn', tipo:'Monstruo', poder:206},
    {id:112, nombre:'Rhydon', tipo:'Monstruo', poder:207},
    {id:113, nombre:'Chansey', tipo:'Hada', poder:217},
    {id:114, nombre:'Tangela', tipo:'Planta', poder:179},
    {id:115, nombre:'Kangaskhan', tipo:'Monstruo', poder:205},
    {id:116, nombre:'Horsea', tipo:'Agua 1', poder:186},
    {id:117, nombre:'Seadra', tipo:'Agua 1', poder:187},
    {id:118, nombre:'Goldeen', tipo:'Agua 2', poder:78},
    {id:119, nombre:'Seaking', tipo:'Agua 2', poder:79},
    {id:120, nombre:'Staryu', tipo:'Agua 3', poder:167},
    {id:121, nombre:'Starmie', tipo:'Agua 3', poder:168},
    {id:122, nombre:'Mr. Mime', tipo:'Humanoide', poder:156},
    {id:123, nombre:'Scyther', tipo:'Bicho', poder:110},
    {id:124, nombre:'Jynx', tipo:'Humanoide', poder:153},
    {id:125, nombre:'Electabuzz', tipo:'Humanoide', poder:155},
    {id:126, nombre:'Magmar', tipo:'Humanoide', poder:151},
    {id:127, nombre:'Pinsir', tipo:'Bicho', poder:112},
    {id:128, nombre:'Tauros', tipo:'Campo', poder:148},
    {id:129, nombre:'Magikarp', tipo:'Agua 2', poder:76},
    {id:130, nombre:'Gyarados', tipo:'Agua 2', poder:77},
    {id:131, nombre:'Lapras', tipo:'Monstruo', poder:219},
    {id:132, nombre:'Ditto', tipo:'Ditto', poder:92},
    {id:133, nombre:'Eevee', tipo:'Campo', poder:180},
    {id:134, nombre:'Vaporeon', tipo:'Campo', poder:181},
    {id:135, nombre:'Jolteon', tipo:'Campo', poder:182},
    {id:136, nombre:'Flareon', tipo:'Campo', poder:183},
    {id:137, nombre:'Porygon', tipo:'Mineral', poder:215},
    {id:138, nombre:'Omanyte', tipo:'Agua 1', poder:220},
    {id:139, nombre:'Omastar', tipo:'Agua 1', poder:221},
    {id:140, nombre:'Kabuto', tipo:'Agua 1', poder:222},
    {id:141, nombre:'Kabutops', tipo:'Agua 1', poder:223},
    {id:142, nombre:'Aerodactyl', tipo:'Volador', poder:224},
    {id:143, nombre:'Snorlax', tipo:'Monstruo', poder:225},
    {id:144, nombre:'Articuno', tipo:'Ninguno', poder:235},
    {id:145, nombre:'Zapdos', tipo:'Ninguno', poder:236},
    {id:146, nombre:'Moltres', tipo:'Ninguno', poder:237},
    {id:147, nombre:'Dratini', tipo:'Agua 1', poder:241},
    {id:148, nombre:'Dragonair', tipo:'Agua 1', poder:242},
    {id:149, nombre:'Dragonite', tipo:'Agua 1', poder:243},
    {id:150, nombre:'Mewtwo', tipo:'Ninguno', poder:249},
    {id:151, nombre:'Mew', tipo:'Ninguno', poder:250}
    

  ]
 
    
}
